#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

src=$1
tmp="${src}.js"

set -e
$DIR/bundle-ls --watch "$src" --out "$tmp" --force
bundle_pid=$!

cleanup(){
    echo "Cleaning up temporary file ($tmp)"
    rm $tmp 2> /dev/null
    kill $bundle_pid 2>/dev/null || true
}
trap cleanup EXIT

echo "Go to chrome://inspect/#devices"
[[ -n $BREAK_ON_START ]] && _BRK="-brk"
$DIR/watch-run $tmp --notify node --enable-source-maps --inspect${_BRK} $tmp 
wait # for build.sh's --watch mode. 
