#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export NODE_MODULES="$(realpath "$DIR/node_modules"):./"

lsFile="$1"
[ $lsFile ] || { echo "Filename is required."; exit 5; }
jsFile="__tmp_${lsFile%.ls}.js"
browserify -t browserify-livescript --extension "ls" --debug --node $lsFile -o $jsFile
if [ "$?" == "0" ]; then
    node -r source-map-support/register --inspect-brk $jsFile
fi
