(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by LiveScript 1.4.0
var sleep, i, this$ = this;
sleep = function(f, ms){
  return setTimeout(ms, f);
};
console.log("hello!");
i = 0;
(function lo(op){
  console.log("looping... " + (i++));
  return sleep(2000, function(){
    if (i > 20) {
      return op();
    }
    debugger;
    return lo(op);
  });
})(function(){
  return console.log("Ended.");
});



},{}]},{},[1])
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uLy4uLy4uLy4uLy4uLy4uLy4uL3Vzci9saWIvbm9kZV9tb2R1bGVzL2Jyb3dzZXJpZnkvbm9kZV9tb2R1bGVzL2Jyb3dzZXItcGFjay9fcHJlbHVkZS5qcyIsIi9ob21lL2NlcmVtY2VtLy5zZGExL2NjYS9yZW1vdGVzL3NjYWRhLWdhdGV3YXlzL2Nhc2VkLTU5NmJjODgxL2RlYnVnZ2luZy1saXZlc2NyaXB0L2hlbGxvLmxzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBOzs7QUNDQSxLQUFNLENBQUEsQ0FBQSxDQUFFLFFBQUEsQ0FBQSxDQUFBLEVBQUEsRUFBQTtTQUFXLFdBQVksSUFBSSxDQUFKOztBQUUvQixPQUFPLENBQUMsSUFBWSxRQUFBO0FBQ3BCLENBQUUsQ0FBQSxDQUFBLENBQUU7Q0FDRCxRQUFBLENBQUEsRUFBQSxDQUFBLEVBQUE7RUFDQyxPQUFPLENBQUMsSUFBSSxhQUFBLENBQUEsQ0FBQSxDQUFZLENBQUUsQ0FBQSxFQUFHLENBQXJCO1NBQ0wsTUFBTTtJQUNFLElBQUcsQ0FBRSxDQUFBLENBQUEsQ0FBRSxFQUFQO01BQVgsTUFBQSxDQUFPLEVBQVAsQ0FBUyxDQUFUOztJQUNBO1dBQ0EsR0FBRyxFQUFEO0dBSE87O1NBSWIsT0FBTyxDQUFDLElBQVksUUFBQSIsImZpbGUiOiJnZW5lcmF0ZWQuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlc0NvbnRlbnQiOlsiKGZ1bmN0aW9uIGUodCxuLHIpe2Z1bmN0aW9uIHMobyx1KXtpZighbltvXSl7aWYoIXRbb10pe3ZhciBhPXR5cGVvZiByZXF1aXJlPT1cImZ1bmN0aW9uXCImJnJlcXVpcmU7aWYoIXUmJmEpcmV0dXJuIGEobywhMCk7aWYoaSlyZXR1cm4gaShvLCEwKTt2YXIgZj1uZXcgRXJyb3IoXCJDYW5ub3QgZmluZCBtb2R1bGUgJ1wiK28rXCInXCIpO3Rocm93IGYuY29kZT1cIk1PRFVMRV9OT1RfRk9VTkRcIixmfXZhciBsPW5bb109e2V4cG9ydHM6e319O3Rbb11bMF0uY2FsbChsLmV4cG9ydHMsZnVuY3Rpb24oZSl7dmFyIG49dFtvXVsxXVtlXTtyZXR1cm4gcyhuP246ZSl9LGwsbC5leHBvcnRzLGUsdCxuLHIpfXJldHVybiBuW29dLmV4cG9ydHN9dmFyIGk9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtmb3IodmFyIG89MDtvPHIubGVuZ3RoO28rKylzKHJbb10pO3JldHVybiBzfSkiLCIjcmVxdWlyZSEgJy4vbXktbGliJzoge3NsZWVwfVxuc2xlZXAgPSAoZiwgbXMpIC0+IHNldC10aW1lb3V0IG1zLCBmXG5cbmNvbnNvbGUubG9nIFwiaGVsbG8hXCJcbmkgPSAwXG48fiA6bG8ob3ApIH4+XG4gICAgY29uc29sZS5sb2cgXCJsb29waW5nLi4uICN7aSsrfVwiXG4gICAgPH4gc2xlZXAgMjAwMG1zXG4gICAgcmV0dXJuIG9wISBpZiBpID4gMjBcbiAgICBkZWJ1Z2dlclxuICAgIGxvKG9wKVxuY29uc29sZS5sb2cgXCJFbmRlZC5cIlxuIl19
