#!/bin/bash
set -u

### Set initial time of file
file=${1:-}
[[ -n $file ]] || { echo "Filename to be watched must be supplied"; exit 2; }
shift
cmd=${@:-}
[[ -n $cmd ]] || { echo "Command must be supplied"; exit 2; }
LTIME=
CMD_PID=

cleanup(){
    [[ -n $CMD_PID ]] && kill $CMD_PID
}
trap cleanup EXIT

while :; do
   ATIME=`stat -c %Z "$file"`
   if [[ "$ATIME" != "$LTIME" ]]; then
        #echo "RUN COMMAND, $ATIME"
        if [[ -n $CMD_PID ]]; then
            echo "---------------------------------------"
            echo "|             Restarting...           |"
            echo "---------------------------------------"
            kill $CMD_PID
        fi
        $cmd &
        CMD_PID=$!
        LTIME=$ATIME
   fi
   sleep 2
done
